ASP.NET MVC/Homework/10. Kendo-UI-ASP.NET-MVC-Wrappers/Web/Working-with-Data.Web/Controllers/PostsController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Working_with_Data.Data.UnitOfWork;
using Working_with_Data.Models;

namespace Working_with_Data.Web.Controllers
{
    public class PostsController : Controller
    {
        private UowData Data = new UowData();

        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult AutocompleteData()
        {
             var result = Data.Tweets.All().Select(x => x.Content).ToArray();
           // var result = new[] { "asfas", "awdasd", "assdasdasd" };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            var tweets = this.Data.Tweets.All().AsQueryable().ToDataSourceResult(request);

            return Json(tweets);
        }

        [HttpPost]
        public ActionResult Create([DataSourceRequest]DataSourceRequest request, Tweet viewModel)
        {
            if(viewModel != null && this.ModelState.IsValid)
            {
                var tweet = new Tweet();

                var content = viewModel.Content.Split(' ');

                for (int i = 0; i < content.Length; i++)
                {
                    var word = content[i];
                    if (content[i].StartsWith("#"))
                    {

                        var exists = Data.Tags.All().Where(x => x.Name == word).FirstOrDefault();
                        if (exists == null)
                        {
                            var newTag = new Tag() { Name = content[i] };
                            Data.Tags.Add(newTag);
                            Data.SaveChanges();
                            tweet.Tags.Add(newTag);
                        }
                        else
                        {
                            tweet.Tags.Add(exists);
                        }
                    }
                }

                tweet.Content = viewModel.Content;
                tweet.UserId = this.User.Identity.GetUserId();
                tweet.CreatedOn = DateTime.Now;

                Data.Tweets.Add(tweet);
                Data.SaveChanges();

                return Json(new[] { tweet }.ToDataSourceResult(request));
            }

            return Json("?");
        }

        [HttpPost]
        public ActionResult Update([DataSourceRequest]DataSourceRequest request, Tweet viewModel)
        {
            if (viewModel != null && this.ModelState.IsValid)
            {

                var tweet = this.Data.Tweets.GetById(viewModel.Id);

                var content = viewModel.Content.Split(' ');

                for (int i = 0; i < content.Length; i++)
                {
                    var word = content[i];
                    if (content[i].StartsWith("#"))
                    {

                        var exists = Data.Tags.All().Where(x => x.Name == word).FirstOrDefault();
                        if (exists == null)
                        {
                            var newTag = new Tag() { Name = content[i] };
                            Data.Tags.Add(newTag);
                            Data.SaveChanges();
                            tweet.Tags.Add(newTag);
                        }
                        else
                        {
                            tweet.Tags.Add(exists);
                        }
                    }
                }

                tweet.Content = viewModel.Content;
                tweet.UserId = this.User.Identity.GetUserId();
                tweet.CreatedOn = DateTime.Now;

                Data.Tweets.Add(tweet);
                Data.SaveChanges();

                return Json(new[] { tweet }.ToDataSourceResult(request));
            }

            return Json("?");
        }

        [HttpPost]
        public ActionResult Destroy([DataSourceRequest]DataSourceRequest request, Tweet viewModel)
        {
            var tweet = this.Data.Tweets.GetById(viewModel.Id);

            Data.Tweets.Delete(tweet);
                Data.SaveChanges();

            return Json(new[] { tweet }.ToDataSourceResult(request));
        }
    }
}

ASP.NET MVC/Homework/10. Kendo-UI-ASP.NET-MVC-Wrappers/Web/Working-with-Data.Web/Controllers/TweetsController.cs
namespace Working_with_Data.Web.Controllers
{
    using Data.UnitOfWork;
    using Kendo.Mvc.Extensions;
    using Kendo.Mvc.UI;
    using Microsoft.AspNet.Identity;
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Working_with_Data.Models;

    public class TweetsController : Controller
    {
        private UowData Data = new UowData();

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult MyTweets()
        {
            var id = this.User.Identity.GetUserId();
            var tweets = Data.Tweets.All().Where(x => x.UserId == id).ToList();
            return View(tweets);
        }

        public ActionResult Taged(string name)
        {
            var tag = "#" + name;
            var tweets = Data.Tweets.All().Where(x => x.Tags.Any(z => z.Name == tag)).ToList();

            return View(tweets);
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tweet viewModel)
        {
            if (viewModel != null && this.ModelState.IsValid)
            {
                var tweet = new Tweet();

                var content = viewModel.Content.Split(' ');

                for (int i = 0; i < content.Length; i++)
                {
                    var word = content[i];
                    if (content[i].StartsWith("#"))
                    {
                       
                        var exists = Data.Tags.All().Where(x => x.Name == word).FirstOrDefault();
                        if (exists == null)
                        {
                            var newTag = new Tag() { Name = content[i] };
                            Data.Tags.Add(newTag);
                            Data.SaveChanges();
                            tweet.Tags.Add(newTag);
                        }
                        else
                        {
                            tweet.Tags.Add(exists);
                        }
                    }
                }

                tweet.Content = viewModel.Content;
                tweet.UserId = this.User.Identity.GetUserId();
                tweet.CreatedOn = DateTime.Now;

                Data.Tweets.Add(tweet);
                Data.SaveChanges();

                return RedirectToAction("MyTweets");
            }

            return View(viewModel);
        }

        public JsonResult GetTweetsByUser(string id)
        {
            var tweets = Data.Tweets.All().Where(x => x.UserId == id).Select( x => 
                new {

                Content = x.Content,
                User = x.User,
                CreatedOn = x.CreatedOn,


                }).ToList();
            return Json(tweets, JsonRequestBehavior.AllowGet);
        }
    }
}

ASP.NET MVC/Homework/10. Kendo-UI-ASP.NET-MVC-Wrappers/Web/Working-with-Data.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/kendo-css")
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TweetMe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("All tweets", "Index", "Posts", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_MenuPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASP.NET MVC/Homework/10. Kendo-UI-ASP.NET-MVC-Wrappers/Web/Working-with-Data.Web/Views/Shared/_MenuPartial.cshtml
<ul class="nav navbar-nav">
    @if (User.Identity.IsAuthenticated)
    {
        <li>@Html.ActionLink("Make tweet", "Create", "Tweets", null, null)</li>
    }

    @if (User.IsInRole("Admin"))
    {
        <li>@Html.ActionLink("Administration", "Admin", "Admin", new { area = "Administration" }, null)</li>
    }
</ul>

ASP.NET MVC/Homework/10. Kendo-UI-ASP.NET-MVC-Wrappers/Web/Working-with-Data.Web/Views/Shared/_TweetsList.cshtml
@model ICollection<Working_with_Data.Models.Tweet>

<table class="table table-bordered table-condensed">
    @foreach (var tweet in Model)
    {

        var content = tweet.Content.Split(' ');

        for (int i = 0; i < content.Length; i++)
        {
            if (content[i].StartsWith("#"))
            {
                content[i] = "<a href=Taged?name=" + content[i].Substring(1) + ">" + content[i] + "</a>";
            }
        }

        var newContent = string.Join(" ", content);



        <tr class="form-group">
            <td class="col-md-2">
                @Html.Raw(newContent)
                <small class="help-block">Created on:<i>@Html.DisplayFor(x => tweet.CreatedOn)</i></small>
            </td>
        </tr>
    }
</table>